// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.3
// source: proto/phnxsvc.proto

package multimarket

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryFeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerToken string                 `protobuf:"bytes,1,opt,name=consumer_token,json=consumerToken,proto3" json:"consumer_token,omitempty"`
	ChainId       uint64                 `protobuf:"varint,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryFeeRequest) Reset() {
	*x = QueryFeeRequest{}
	mi := &file_proto_phnxsvc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryFeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryFeeRequest) ProtoMessage() {}

func (x *QueryFeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_phnxsvc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryFeeRequest.ProtoReflect.Descriptor instead.
func (*QueryFeeRequest) Descriptor() ([]byte, []int) {
	return file_proto_phnxsvc_proto_rawDescGZIP(), []int{0}
}

func (x *QueryFeeRequest) GetConsumerToken() string {
	if x != nil {
		return x.ConsumerToken
	}
	return ""
}

func (x *QueryFeeRequest) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

type QueryFeeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReturnCode    uint64                 `protobuf:"varint,1,opt,name=return_code,json=returnCode,proto3" json:"return_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryFeeResponse) Reset() {
	*x = QueryFeeResponse{}
	mi := &file_proto_phnxsvc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryFeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryFeeResponse) ProtoMessage() {}

func (x *QueryFeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_phnxsvc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryFeeResponse.ProtoReflect.Descriptor instead.
func (*QueryFeeResponse) Descriptor() ([]byte, []int) {
	return file_proto_phnxsvc_proto_rawDescGZIP(), []int{1}
}

func (x *QueryFeeResponse) GetReturnCode() uint64 {
	if x != nil {
		return x.ReturnCode
	}
	return 0
}

func (x *QueryFeeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_phnxsvc_proto protoreflect.FileDescriptor

const file_proto_phnxsvc_proto_rawDesc = "" +
	"\n" +
	"\x13proto/phnxsvc.proto\x12\x14multimarket.protocol\"S\n" +
	"\x0fQueryFeeRequest\x12%\n" +
	"\x0econsumer_token\x18\x01 \x01(\tR\rconsumerToken\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\x04R\achainId\"M\n" +
	"\x10QueryFeeResponse\x12\x1f\n" +
	"\vreturn_code\x18\x01 \x01(\x04R\n" +
	"returnCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2w\n" +
	"\x0fPhoenixServices\x12d\n" +
	"\x11queryFeeByChainId\x12%.multimarket.protocol.QueryFeeRequest\x1a&.multimarket.protocol.QueryFeeResponse\"\x00B/\n" +
	"\x18com.multimarket.protocolZ\x13./proto/multimarketb\x06proto3"

var (
	file_proto_phnxsvc_proto_rawDescOnce sync.Once
	file_proto_phnxsvc_proto_rawDescData []byte
)

func file_proto_phnxsvc_proto_rawDescGZIP() []byte {
	file_proto_phnxsvc_proto_rawDescOnce.Do(func() {
		file_proto_phnxsvc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_phnxsvc_proto_rawDesc), len(file_proto_phnxsvc_proto_rawDesc)))
	})
	return file_proto_phnxsvc_proto_rawDescData
}

var file_proto_phnxsvc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_phnxsvc_proto_goTypes = []any{
	(*QueryFeeRequest)(nil),  // 0: multimarket.protocol.QueryFeeRequest
	(*QueryFeeResponse)(nil), // 1: multimarket.protocol.QueryFeeResponse
}
var file_proto_phnxsvc_proto_depIdxs = []int32{
	0, // 0: multimarket.protocol.PhoenixServices.queryFeeByChainId:input_type -> multimarket.protocol.QueryFeeRequest
	1, // 1: multimarket.protocol.PhoenixServices.queryFeeByChainId:output_type -> multimarket.protocol.QueryFeeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_phnxsvc_proto_init() }
func file_proto_phnxsvc_proto_init() {
	if File_proto_phnxsvc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_phnxsvc_proto_rawDesc), len(file_proto_phnxsvc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_phnxsvc_proto_goTypes,
		DependencyIndexes: file_proto_phnxsvc_proto_depIdxs,
		MessageInfos:      file_proto_phnxsvc_proto_msgTypes,
	}.Build()
	File_proto_phnxsvc_proto = out.File
	file_proto_phnxsvc_proto_goTypes = nil
	file_proto_phnxsvc_proto_depIdxs = nil
}
