// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: proto/phnxsvc.proto

package multimarket

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PhoenixServices_QueryFeeByChainId_FullMethodName = "/multimarket.protocol.PhoenixServices/queryFeeByChainId"
)

// PhoenixServicesClient is the client API for PhoenixServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PhoenixServicesClient interface {
	QueryFeeByChainId(ctx context.Context, in *QueryFeeRequest, opts ...grpc.CallOption) (*QueryFeeResponse, error)
}

type phoenixServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewPhoenixServicesClient(cc grpc.ClientConnInterface) PhoenixServicesClient {
	return &phoenixServicesClient{cc}
}

func (c *phoenixServicesClient) QueryFeeByChainId(ctx context.Context, in *QueryFeeRequest, opts ...grpc.CallOption) (*QueryFeeResponse, error) {
	out := new(QueryFeeResponse)
	err := c.cc.Invoke(ctx, PhoenixServices_QueryFeeByChainId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PhoenixServicesServer is the server API for PhoenixServices service.
// All implementations should embed UnimplementedPhoenixServicesServer
// for forward compatibility
type PhoenixServicesServer interface {
	QueryFeeByChainId(context.Context, *QueryFeeRequest) (*QueryFeeResponse, error)
}

// UnimplementedPhoenixServicesServer should be embedded to have forward compatible implementations.
type UnimplementedPhoenixServicesServer struct {
}

func (UnimplementedPhoenixServicesServer) QueryFeeByChainId(context.Context, *QueryFeeRequest) (*QueryFeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryFeeByChainId not implemented")
}

// UnsafePhoenixServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PhoenixServicesServer will
// result in compilation errors.
type UnsafePhoenixServicesServer interface {
	mustEmbedUnimplementedPhoenixServicesServer()
}

func RegisterPhoenixServicesServer(s grpc.ServiceRegistrar, srv PhoenixServicesServer) {
	s.RegisterService(&PhoenixServices_ServiceDesc, srv)
}

func _PhoenixServices_QueryFeeByChainId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhoenixServicesServer).QueryFeeByChainId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PhoenixServices_QueryFeeByChainId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhoenixServicesServer).QueryFeeByChainId(ctx, req.(*QueryFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PhoenixServices_ServiceDesc is the grpc.ServiceDesc for PhoenixServices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PhoenixServices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "multimarket.protocol.PhoenixServices",
	HandlerType: (*PhoenixServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "queryFeeByChainId",
			Handler:    _PhoenixServices_QueryFeeByChainId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/phnxsvc.proto",
}
